### ISSUE TITLE
Questions about performance of baselines

### ISSUE THREAD

**Issue by rainbow979** [robot-colosseum/robot-colosseum#11]
I'm not sure whether I understand correctly.
Are success rates of all baselines at most 40% for all tasks even without variants?

**Comment by rainbow979** [comment]
I found the detailed results in the appendix. But I have another question: why performance increases with variants in some tasks. For example, "stack cups" has 0% success rate without variants while has 40% success rate with Light_Color

**Comment by jiafei1224** [comment]
The performance increase might be due to many factors of the policy, for example pre-training with R3M and MVP could contain data distribution that helps with certain perturbation factors, while models such as VoxPoser could be performed better with varying texture which is more representative to real-world data that VLMs are trained on. However, this odd case does not occur too commonly.
