### ISSUE TITLE
Code Migration Timeline

### ISSUE THREAD

**Issue by GuanxingLu** [robot-colosseum/robot-colosseum#3]
Hello there, thanks for your great work! I have noticed that this repo is under development, and I'm curious about the timeline for the code migration process. Additionally, can you share any insights regarding the main areas where this repository might be lacking now?

**Comment by wpumacay** [comment]
Hi @GuanxingLu, sorry for the delayed response. We're currently working on refactoring the RVT baseline, and we have some new variation factors that we added to our internal codebase regarding physical properties (friction and mass). In the next week or two we should have these in the repo. We'll release RVT as the core baseline, and update the documentation with pointers on how to integrate our benchmark for usage with other codebases.

Regarding your second question, could you elaborate a little more ? :sweat_smile: . There are quite a few areas we wish to improve. For example, for the variation factors we currently have some issues with the texture variation, which can be fixed by upgrading to the latest version of `CoppeliaSim` and [`PyRep`](https://github.com/stepjam/PyRep/tree/4.6.0.beta). We'll upgrade once the new version of `PyRep` is stable.

**Comment by GuanxingLu** [comment]
Thanks! Just ignore my second question.
